command:
  # Nachricht, die angezeigt wird, wenn der Spieler Hilfe zum /back-Befehl anfordert
  help: '%teracore_prefix% &e❓ &7Verwende &f/back &7, um dich zur letzten Position zu teleportieren.'

  args0:
    # Nachricht, die angezeigt wird, wenn der Spieler erfolgreich teleportiert wird
    usage: '%teracore_prefix% &a✔ &7Du wurdest erfolgreich zur letzten Position teleportiert!'

    # Nachricht, wenn keine Back-Position gefunden wurde
    failed: '%teracore_prefix% &c✖ &7Es wurde keine gespeicherte Position gefunden!'

    # Berechtigung, die erforderlich ist, um den /back-Befehl zu verwenden
    permission: 'teracore.back'
