command:
  list:
    # Nachricht, die angezeigt wird, wenn der Spieler eine Liste seiner gesetzten Homes anfordert
    message: '%teracore_prefix% &e⭐ &7Verfügbare Homes: &e'
    
    # Nachricht, die angezeigt wird, wenn ein angegebenes Home nicht gefunden wurde
    failed: '%teracore_prefix% &4✘ &cDas Home &e%home% &cwurde nicht gefunden!'
    
    # Nachricht, die angezeigt wird, wenn der Spieler erfolgreich zu einem Home teleportiert wurde
    teleport: '%teracore_prefix% &a✔ &7Du wurdest zum Home &e%home% &7teleportiert!'
    
    # Trennzeichen, das verwendet wird, um mehrere Homes in der Liste zu trennen
    split: '&7, &e'
    
    # Nachricht, die angezeigt wird, wenn der Spieler keine Homes gesetzt hat
    empty: '%teracore_prefix% &c✘ Du hast noch keine Homes gesetzt!'

  sethome:
    # Nachricht, die erklärt, wie der /sethome-Befehl verwendet werden kann
    help: '%teracore_prefix% &e❓ &7Verwendung: &e/sethome <Name>'
    
    # Nachricht, die angezeigt wird, wenn ein Home erfolgreich gesetzt wurde
    message: '%teracore_prefix% &a✔ &7Home &e%home% &7erfolgreich gesetzt!'
    
    # Nachricht, die angezeigt wird, wenn versucht wird, ein Home mit einem bereits existierenden Namen zu setzen
    failed: '%teracore_prefix% &4✘ &cDas Home &e%home% &cexistiert bereits!'
    
    # Erforderliche Berechtigung, um den /sethome-Befehl zu verwenden
    permission: teracore.sethome

    maxhome:
      # Aktiviert die Begrenzung der maximal erlaubten Homes
      enabled: true
      
      # Maximale Anzahl an Homes, die ein normaler Spieler setzen darf
      max_home: 40  # Standardmäßig dürfen Spieler bis zu 40 Homes setzen
      
      # Wenn die Anzahl in der Berechtigung (`teracore.maxhome.%amount%`) höher ist als der
      # Wert bei max_home, hat der Spieler 0 Homes zur Verfügung.
      
      # Berechtigung, die die maximale Anzahl an Homes pro Spieler definiert
      permission: 'teracore.maxhome.%amount%'
      
      # Nachricht, die angezeigt wird, wenn ein Spieler versucht, mehr Homes zu setzen als erlaubt
      message: '%teracore_prefix% &4✘ &cDu kannst nicht mehr als &e%amount% &cHomes setzen!'
      
      admin:
        # Ermöglicht Administratoren, das Limit für Homes zu ignorieren
        ignore_limit: false  # Wenn "true", können Administratoren beliebig viele Homes setzen
        
        # Berechtigung, die erforderlich ist, damit Administratoren die speziellen Einstellungen nutzen können
        permission: 'teracore.maxhome.ignorelimit'

  delhome:
    # Nachricht, die erklärt, wie der /delhome-Befehl verwendet werden kann
    help: '%teracore_prefix% &e❓ &7Verwendung: &e/delhome <Name>'
    
    # Nachricht, die angezeigt wird, wenn ein Home erfolgreich gelöscht wurde
    message: '%teracore_prefix% &a✔ &7Das Home &e%home% &7wurde erfolgreich gelöscht!'
    
    # Nachricht, die angezeigt wird, wenn das zu löschende Home nicht existiert
    failed: '%teracore_prefix% &4✘ &cDas Home &e%home% &cwurde nicht gefunden!'
    
    # Erforderliche Berechtigung, um den /delhome-Befehl zu verwenden
    permission: teracore.delhome

  movehome:
    # Nachricht, die erklärt, wie der /movehome-Befehl verwendet werden kann
    help: '%teracore_prefix% &e❓ &7Verwendung: &e/movehome <Name>'

    # Nachricht, die angezeigt wird, wenn ein Home erfolgreich verschoben wurde
    message: '%teracore_prefix% &a✔ &7Home &e%home% &7erfolgreich verschoben!'

    # Nachricht, die angezeigt wird, wenn das angegebene Home nicht existiert
    failed: '%teracore_prefix% &4✘ &cDas Home &e%home% &cwurde nicht gefunden!'

    # Erforderliche Berechtigung, um den /movehome-Befehl zu verwenden
    permission: teracore.movehome