kick:
  # Nachricht, die an den Spieler gesendet wird, wenn er gekickt wird
  message:
    - '%teracore_name%'
    - ' '
    - '&c✖ &7Du wurdest gekickt! &c✖'
    - '&a⚑ &7Von: &e%sender%'
    - '&6❖ &7Grund: &e%reason%'
    - ' '
    - '%teracore_name%'

  # Nachricht, wenn kein Grund angegeben wurde
  no_reason: 'Kein Grund angegeben!'

command:
  # Hilfe-Nachricht für den Kick-Befehl
  help: '%teracore_prefix% &e❓ &7/kick <Spieler> <Grund>'
  
  # Nachricht, die angezeigt wird, wenn der Kick erfolgreich war
  usage: '%teracore_prefix% &c🚫 &7Der Spieler &e%player% &7wurde von &e%sender% &7gekickt!'
  
  # Berechtigung, die erforderlich ist, um den Kick-Befehl auszuführen
  permission: 'teracore.kick'
