placeholder:
  # Platzhalter für Typen, die im Teleport-Befehl verwendet werden
  type: 
    location: 'location'
    player: 'player'

command:
  # Hilfe-Nachricht, die den Spielern erklärt, wie der Teleport-Befehl verwendet wird
  help: '%teracore_prefix% &e❓ &7/teleport <Spieler/Location> <Spieler/Location>'
  
  # Argument 1 (Teleportiert den Spieler zu einer Location oder einem anderen Spieler)
  args1:
    # Nachricht, die anzeigt, dass der Spieler erfolgreich teleportiert wurde
    usage: '%teracore_prefix% &e🌍 &7Du wurdest zu &e%location% &7teleportiert!'
    
    # Berechtigung, um sich zu einer Location oder einem Spieler zu teleportieren
    permission: 'teracore.teleport.%type%'

  # Argument 2 (Teleportiert einen anderen Spieler zu einer Location oder einem anderen Spieler)
  args2:
    # Nachricht, die anzeigt, dass der Spieler erfolgreich zu einer Location teleportiert wurde
    usage: '%teracore_prefix% &e🌍 &7Der Spieler &e%player% &7wurde zu &e%location% &7teleportiert!'
    
    # Berechtigung, um einen anderen Spieler zu teleportieren
    permission: 'teracore.teleport.%type%.other'
