teleport:
  # Wer die Effekte und Sounds des Teleports sehen/hören kann
  see-and-hear:
    online_player: true  # Online-Spieler sehen/hören den Teleport-Effekt
    sender: true  # Der Teleportierende selbst sieht/hört den Effekt
  
  # Steuerung, wann Effekte und Sounds deaktiviert werden sollen
  black-list:
    enabled: true
    gamemode:
      enabled: true
      list:
        - SPECTATOR  # Kein Effekt im Spectator-Modus
        - ADVENTURE  # Kein Effekt im Adventure-Modus
    world:
      enabled: false
      list:
        - world1  # Kein Effekt in "world1"
        - world2  # Kein Effekt in "world2"
    permission:
      enabled: false
      permission: 'teracore.teleport.noeffect'  # Kein Effekt bei Spielern mit dieser Berechtigung

  # Teleport-Soundeffekteinstellungen
  sound:
    enabled: true
    type: ENTITY_ENDERMAN_TELEPORT
    pitch: 1
    volume: 0.3
  
  # Teleport-Partikeleinstellungen
  particle:
    enabled: true
    color: AQUA
    size: 1.5
    radius: 1
    height: 2.5
    spread: 0.5
  
  # Einstellungen für die Teleport-Verzögerung
  delay:
    enabled: true
    seconds: 5
    bypass:
      enabled: false
      permission: 'teracore.teleport.delay.bypass'
    join-cooldown-second: 5  # Zeit nach dem Join, bevor der Teleport-Delay greift (z. B. für Spawn-Plugins)

    chat:
      enabled: true
      message: '%teracore_prefix% &b✦ &7Du wirst in &e%seconds% Sekunden &7teleportiert!'
      successful: '%teracore_prefix% &a✔ &7Du wurdest erfolgreich teleportiert!'
      failed: '%teracore_prefix% &c✖ &7Der Teleport wurde abgebrochen!'

    # Countdown-Partikeleffekteinstellungen
    particle:
      enabled: true
      color: YELLOW
      size: 1.5
      radius: 1
      height: 2.5
      spread: 0.5
    
    # Countdown-Soundeffekteinstellungen
    sound:
      enabled: true
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      pitch: 1
      volume: 0.3
