tempban:
  # Zeitangaben, die für den temporären Bann verwendet werden (Tage, Stunden, Minuten, Sekunden)
  time: 
    days: 'Tage'     # Platzhalter für Tage
    hours: 'Stunden'  # Platzhalter für Stunden
    minutes: 'Minuten'  # Platzhalter für Minuten
    seconds: 'Sekunden'  # Platzhalter für Sekunden

command:
  # Hilfe-Nachricht, die erklärt, wie der /tempban-Befehl verwendet wird
  help: '%teracore_prefix% &e❓ &7/tempban <Spieler> <Zeit> <Grund>'
  
  # Detaillierte Hilfe, um den Befehl korrekt zu benutzen, einschließlich der verwendeten Zeitabkürzungen
  help2: '%teracore_prefix% &e❓ &bd &7= &eTage&7, &bh &7= &eStunden&7, &bm &7= &eMinuten&7, &bs &7= &eSekunden'

  # Beispiel für die Verwendung des Befehls
  help3: '%teracore_prefix% &e❓ &6Beispiel: /tempban Steve 10d frech'

  # Nachricht, die angezeigt wird, wenn ein Spieler erfolgreich temporär gebannt wird
  usage: '%teracore_prefix% &c🚫 &7Der Spieler &e%player% &7wurde von &e%sender% &7temporär gebannt!'

  # Nachricht, die angezeigt wird, wenn der Versuch fehlschlägt (z.B. Spieler ist bereits gebannt)
  failed: '%teracore_prefix% &4🚫 &cDer Spieler &e%player% &cwurde bereits gebannt!'

  # Berechtigung, die benötigt wird, um den /tempban-Befehl auszuführen
  permission: 'teracore.tempban'
