command:
  list:
    # Nachricht, wenn die verfügbaren Warps angezeigt werden
    message: '%teracore_prefix% &e⭐ &7Verfügbare Warps: &e'
    
    # Nachricht, wenn der angegebene Warp nicht gefunden wird
    failed: '%teracore_prefix% &4✘ &cWarp &e%warp% &cwurde nicht gefunden!'
    
    # Nachricht, wenn der Spieler erfolgreich zu einem Warp teleportiert wurde
    teleport: '%teracore_prefix% &a✔ &7Du wurdest zu &e%warp% &7teleportiert!'
    
    # Trennzeichen zwischen den Warp-Namen in der Liste
    split: '&7, &e'
    
    # Nachricht, wenn keine Warps gesetzt sind
    empty: '%teracore_prefix% &c✘ Keine Warps gesetzt!'

  setwarp:
    # Hilfe-Nachricht für den Befehl /setwarp
    help: '%teracore_prefix% &e❓ &7Verwende: &e/setwarp <Name>'
    
    # Nachricht, wenn ein Warp erfolgreich gesetzt wurde
    message: '%teracore_prefix% &a✔ &7Warp &e%warp% &7wurde erfolgreich gesetzt!'
    
    # Nachricht, wenn der Warp bereits existiert
    failed: '%teracore_prefix% &4✘ &cWarp &e%warp% &cist bereits gesetzt!'
    
    # Erforderliche Berechtigung für das Setzen eines Warps
    permission: teracore.setwarp

  delwarp:
    # Hilfe-Nachricht für den Befehl /delwarp
    help: '%teracore_prefix% &e❓ &7Verwende: &e/delwarp <Name>'
    
    # Nachricht, wenn ein Warp erfolgreich gelöscht wurde
    message: '%teracore_prefix% &a✔ &7Warp &e%warp% &7wurde erfolgreich gelöscht!'
    
    # Nachricht, wenn der Warp nicht gefunden wird
    failed: '%teracore_prefix% &4✘ &cWarp &e%warp% &cwurde nicht gefunden!'
    
    # Erforderliche Berechtigung für das Löschen eines Warps
    permission: teracore.delwarp
